services:
  ring5-dev:
    build: .
    user: researcher
    ports:
      - 8501:8501
    volumes:
      - .:/home/researcher/workspace
    environment:
      - PYTHONPATH=/home/researcher/workspace
      - STREAMLIT_SERVER_FOLDER_WATCHER_TYPE=poll
    working_dir: /home/researcher/workspace
